// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKYSiXvTCbztJ6iR6XayjRDYDIqI3g2hc',
    appId: '1:245508935109:web:0f568faac98f6a3a2f4fac',
    messagingSenderId: '245508935109',
    projectId: 'link-five-45afa',
    authDomain: 'link-five-45afa.firebaseapp.com',
    storageBucket: 'link-five-45afa.appspot.com',
    measurementId: 'G-0J6B593T88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCde-N6lnuc2Q7gNcUVXdLw2HHTkCb_MJo',
    appId: '1:245508935109:android:63587bed4f8d1b982f4fac',
    messagingSenderId: '245508935109',
    projectId: 'link-five-45afa',
    storageBucket: 'link-five-45afa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcyl9QRui-Xr13cfLtQ309GgpWDfnZmkQ',
    appId: '1:245508935109:ios:0ded73314b38f8ca2f4fac',
    messagingSenderId: '245508935109',
    projectId: 'link-five-45afa',
    storageBucket: 'link-five-45afa.appspot.com',
    iosBundleId: 'me.timothysteward.linkFive',
  );
}
